hakim-theory-sem-2012.pdf: hakim-theory-sem-2012.tex
	pdflatex hakim-theory-sem-2012.tex
	bibtex hakim-theory-sem-2012
	pdflatex hakim-theory-sem-2012.tex
	pdflatex hakim-theory-sem-2012.tex

clean:
	rm -f hakim-theory-sem-2012.pdf
