## -*- python -*-

Import('env')

# name of library built with code in this file
libname = 'lcmup'

sources = ['muParser.cpp',
           'muParserBytecode.cpp', 
           'muParserInt.cpp',
           'muParserTokenReader.cpp',
           'muParserBase.cpp',
           'muParserCallback.cpp',
           'muParserError.cpp',
           ]

myenv = env.Clone()
myenv.Append(CCFLAGS = '-DNDEBUG')

etc_sources = sources

##
# compile sources and add them to list of objects built
##
objs = []
for s in etc_sources:
    o = myenv.Object(s)
    objs.append(o)

##
# Archive into library
##
myenv.Library(libname, objs)
