## -*- python -*-

##
# Build unit-tests for core WarpX classes
##

Import('env')
Import('parenv')

# Include directories
incs = [
    '.',
    '#lib',
    '#etc',
    '#etc/loki/include',
    ]

# Libraries to link to
libs = [
    'lclib',
    'lcloki',
    'lcmup',
        ]

# Library paths
libp = ['../lib',
        '../etc/loki',
        '../etc/mup',
        ]

# add paths and libraries to environment
myenv = env.Clone()
myenv.Append(CPPPATH = incs)
myenv.Prepend(LIBS = libs)
myenv.Append(LIBPATH = libp)

# add paths and libraries to environment
myparenv = parenv.Clone()
myparenv.Append(CPPPATH = incs)
myparenv.Prepend(LIBS = libs)
myparenv.Append(LIBPATH = libp)

# lcany
myenv.Program('lcany', ['lcany.cxx'])

# lcexcept
myenv.Program('lcexcept', ['lcexcept.cxx'])

# lckeyval
myenv.Program('lckeyval', ['lckeyval.cxx'])

# lckeyvaltree
myenv.Program('lckeyvaltree', ['lckeyvaltree.cxx'])

# lckeyvaltreelexer
myenv.Program('lckeyvaltreelexer', ['lckeyvaltreelexer.cxx'])

# lckeyvaltreeparser
myenv.Program('lckeyvaltreeparser', ['lckeyvaltreeparser.cxx'])

# lcobjcreator
myenv.Program('lcobjcreator', ['lcobjcreator.cxx'])

# lclogger
myenv.Program('lclogger', ['lclogger.cxx'])

# lcexprparser
myenv.Program('lcexprparser', ['lcexprparser.cxx'])

if myparenv['parallel']:
    # MPI messaging tests
    myparenv.Program('lcparmpimsg',
                     ['lcparmpimsg.cxx'])
