## -*- python -*-

##
# Unit-tests
##

Import('env')

# Include directories
incs = [
    '.',
    '#lib',
    '#etc',
    '#etc/loki/include',
    '#etc/lua/src',
    ]

# Libraries to link to
libs = [
    'lclib',
    'lcloki',
    'lclua',
        ]

# Library paths
libp = ['../lib',
        '../etc/loki',
        '../etc/lua',
        ]

# add paths and libraries to environment
myenv = env.Clone()
myenv.Append(CPPPATH = incs)
myenv.Prepend(LIBS = libs)
myenv.Append(LIBPATH = libp)

# lcarray
myenv.Program('lcarray', ['lcarray.cxx'])

# lccolmajorindexer
myenv.Program('lccolmajorindexer', ['lccolmajorindexer.cxx'])

# lcfixedvector
myenv.Program('lcfixedvector', ['lcfixedvector.cxx'])

# lcvector
myenv.Program('lcvector', ['lcvector.cxx'])

# lcmatrix
myenv.Program('lcmatrix', ['lcmatrix.cxx'])

# lcsettableobject
myenv.Program('lcsettableobject', ['lcsettableobject.cxx'])

# lckeyval
myenv.Program('lckeyval', ['lckeyval.cxx'])

# lckeyvaltree
myenv.Program('lckeyvaltree', ['lckeyvaltree.cxx'])

# lclua
myenv.Program('lclua', ['lclua.cxx'])
