/**
 * @file	lclogrecordhandler.h
 *
 * @brief	Class for loggers.
 *
 * @version	$Id$
 *
 * Copyright &copy; 2008-2009, Ammar Hakim. Released under Eclipse
 * Licence version 1.0.
 */

#ifndef LC_LOG_RECORD_HANDLER_H
#define LC_LOG_RECORD_HANDLER_H

// std includes
#include <ios>
#include <iostream>

namespace Lucee
{
/**
 * Class to handle log messsages generated by the logging system. This
 * class can not be used directly. Instead, children handlers must
 * provide the needed functionality.
 */
  class LogRecordHandler
  {
    public:
/**
 * Destroy handler.
 */
      virtual ~LogRecordHandler();

/**
 * Write message 'msg' to the output stream.
 *
 * @param msg Message to write to stream.
 */
      virtual void write(const std::string& msg);

    protected:
/**
 * Create new handler, attaching it to the specified stream.
 *
 * @param stream Stream to attach to handler.
 */
      LogRecordHandler(std::ostream& stream);

    private:
/** Reference to output stream */
      std::ostream& _outStream;
  };
}

#endif // LC_LOG_RECORD_HANDLER_H
