hakim-dg-diff-2013.pdf: hakim-dg-diff-2013.tex
	pdflatex hakim-dg-diff-2013.tex
	bibtex hakim-dg-diff-2013
	pdflatex hakim-dg-diff-2013.tex
	pdflatex hakim-dg-diff-2013.tex

clean:
	rm -f hakim-dg-diff-2013.pdf
