## -*- python -*-
##
# Build code and create library
#
# Copyright &copy; 2008-2009, Ammar Hakim.
##

import platform

# determine machine type
mcType = 'generic'
if platform.system() == 'Darwin':
    mcType = 'LUA_USE_LINUX'
elif platform.system() == 'Linux':
    mcType = 'LUA_USE_LINUX'
else:
    print "SET CORRECT PLATFORM TO BUILD LUA"
    Exit(1)

Import('env')
Import('parenv')

incs = [
    '.',
    ]

# make a local copy of the build environment
myenv = env.Clone()
myenv.Append(CPPPATH = incs)
myenv.Append(CCFLAGS = '-DLUA_USE_LINUX')

myparenv = parenv.Clone()
myparenv.Append(CPPPATH = incs)
myparenv.Append(CCFLAGS = '-DLUA_USE_LINUX')

# name of library built with code in this file
libname = 'lclua'

# source files in lib
sources = [
    'lapi.c',
    'ldump.c',
    'lmem.c',
    'lstring.c',
    'lundump.c',
    'lauxlib.c',
    'lfunc.c',
    'loadlib.c',
    'lstrlib.c',
    'lvm.c',
    'lbaselib.c',
    'lgc.c',
    'lobject.c',
    'ltable.c',
    'lzio.c',
    'lcode.c',
    'linit.c',
    'lopcodes.c',
    'ltablib.c',
    'print.c',
    'ldblib.c',
    'liolib.c',
    'loslib.c',
    'ltm.c',
    'ldebug.c',
    'llex.c',
    'lparser.c',
    'lua.c',
    'ldo.c',
    'lmathlib.c',
    'lstate.c',
    'luac.c',
    ]

##
# compile sources and add them to list of objects
##
objs = []
for s in sources:
    o = myenv.Object(s)
    objs.append(o)
    
##
# Archive into library
##
myenv.Library(libname, objs)
